readme.md
will save time for those like me who don't know the default port of MongoDB
=> updates installation howto

server.js
This adds a default-block CSP to cryptpad with the most egregious relaxations of security explained.
=> Add a Content Security Policy to cryptpad server.js

customize.dist/translations/messages.pt-br.js
I've fixed some minor errors and revised some texts in order to provide better sense for the text. 
Beside that, I've reduced the text (keeping it's meaning of course) of the buttons close to the bottom of the front page, since on Firefox, Chrome and Safari, the buttons seems to not be adaptive oriented as the main text divs.
=> Reviewed and fine tuned FP and TOS (Brazilian Portuguese)

customize.dist/translations/messages.es.js
Added all the missing keys in staging! :tada:
=> Update Spanish translation 🇪🇸

customize.dist/translations/messages.es.js
Added all missing Spanish keys, still need to make all terms uniform but good enough for now :)!
=> Spanish translation updated 🎉

www/drive/file.css, www/drive/file.less
In the file manager, add a slight visual clue that elements are interactable. I also changed the padding on the grid view to be a bit more spaced out, as the borders were stuck to the icons before.
=> Add hover on elements in drive and make grid slightly prettier

customize.dist/translations/messages.es.js, customize.dist/translations/messages.fr.js
=> Update FR and ES translations

www/drive/file.css, www/drive/file.less
Various quality of life improvements to /drive 🎉
* (css) prevent huge titles from making overly large rows - max-height on items
* (css) prettier overflow with text-overflow: ellipsis
* (css) add a transparent border when not selected so item size doesnt change and items jump around
=> (CSS) Some improvements to drive

customize.dist/translations/messages.es.js
=> Spanish update 🇪🇸

customize.dist/translations/messages.es.js
Updated with the latest Spanish translation keys!
=> Spanish! 🇪🇸

www/poll/main.js
=> Fix flash of autocomplete in poll

customize.dist/translations/messages.es.js
Spanish updated with new pinpad keys :)
=> Spanish pinpad

customize.dist/translations/messages.es.js
=> Spanish update

customize.dist/translations/messages.es.js
A little spanish update :es: enjoy!
=> Spanish new keys

customize.dist/messages.js, customize.dist/translations/messages.zh.js
add Traditional Chinese translation
=> Traditional Chinese

customize.dist/translations/messages.es.js, customize.dist/translations/messages.fr.js, customize.dist/translations/messages.js, www/poll/index.html, www/poll/main.js, www/poll/poll.css, www/poll/poll.less, www/poll/render.js
Hello again! Here are some more poll improvements 🎉 
* Editing is more visible, turning the column or row blue
* Properly supports disconnecting
* Putting a poll in trash now works as intended
* Added a "show help" button to display the first-time text... might need better text
* Implement multiple choices (Yes ☑️, No ❌, Maybe 〰️, Undecided ❔)
We still need some sort of legend to know what each value means (probably with a bunch of translation keys and some code changes) but this is good enough for now I think!
=> More poll improvements

www/whiteboard/index.html
why ? it doesn't make sense to draw with "0" opacity
=> change minimum opacity

www/poll/main.js
=> Fix poll auto-focus inputs

customize.dist/translations/messages.es.js
The Spanish translation had several issues, mostly related to accent marks and spelling.
=> Fixed spelling issues and improved translation quality.

customize.dist/translations/messages.es.js, customize.dist/translations/messages.fr.js
=> New FR/ES keys

www/file/main.js
Now we have a good looking PDF viewer ❤️
=> Fix PDF.js styles

customize.dist/pages.js, customize.dist/src/less2/include/alertify.less, customize.dist/src/less2/include/colortheme.less, customize.dist/src/less2/include/mediatag.less, customize.dist/translations/messages.js, www/code/code.less, www/code/inner.js, www/code/main.js, www/common/diffMarked.js, www/slide/slide.less
=> UI improvements

customize.dist/pages.js
I changed the social media links for Pierre
=> Changed the social media links for Pierre

readme.md
Added installation hint in Readme.md
- added ansible setup method
=> Updated Readme.md with hint for ansible setup

readme.md
Because this information was lacking and I need to find it quickly (and probably other people).
Don't forget to update this part at each new released.
=> Cryptad version in Readme.md added

customize.dist/translations/messages.fr.js
A small update of the French translation.
=> Update French translation

customize.dist/messages.js, customize.dist/translations/messages.el.js
=> Greek translation

www/code/orgmode.js
More details here: https://github.com/mickael-kerjean/nuage/pull/16
As you can see, the current regex yields some red herrings.
=> Fix Org mode regex.

CHANGELOG.md
=> added changelog.md with version tag and current changes

customize.dist/translations/messages.de.js
Corrected lots of typos, grammar and incomprehensible (machine?) translation. Things can still be improved but at least most of the strangeness should be gone. I also added all strings from messages.js that were not included before.
Somebody needs to check that I did not mess up code/formatting.
=> Total revision of german translation

customize.dist/translations/messages.de.js
=> Update messages.de.js: typo: Markdwon -> Markdown

docker-compose.yml, docs/cryptpad-docker.md
This should fix #301. I'm putting the lessons I learned after deleting all my users on my instance into the documentation, so it shouldn't happen again.
=> Update documentation for Docker usage

www/common/translations/messages.de.js, www/common/translations/messages.js
I have updated the German translation to fix some mistakes and to make it more consistent. There should be no untranslated messages anymore.
Also, I fixed some minor mistakes in English message file. The FAQ states that you cannot change your CryptPad password and you cannot share folders with others. This info seems to be outdated, so I changed it as well.
=> Update German translation

www/drive/app-drive.less
This PR improves how we handle narrow layouts in the drive.
=> Fix horizontal scrollbar in drive

customize.dist/loading.js
This swaps out the font-awesome spinner for one written in css which doesn't oscillate (and has a cool animation)
=> Change loading spinner to custom spinner

Dockerfile
Signed-off-by: Adrian Nöthlich <git@promasu.tech>
=> Bump NodeJS version to 10 to fix #447

Dockerfile
Signed-off-by: Adrian Nöthlich <git@promasu.tech>
=> Update Node to v12 in Dockerfile

Dockerfile
=> Added missing curl

customize.dist/pages/features.js
Shows the premium features panel on `/features.html` only when subscriptions are allowed.
=> List premium features only with subscriptions

customize.dist/pages.js, www/common/application_config_internal.js
Adds a `privacy` option to `application_config_internal.js`, similar to `imprint`.
=> Add privacy policy option

bower.json, www/common/diffMarked.js
=> #571 Adding mathjax svg rendering in code pad

www/form/app-form.less, www/form/inner.js
=> Hackathon 2021

www/checkup/main.js
Signed-off-by: creme <creme@envs.net>
https://matrix.to/#/!LpznxDnFgoUmBSQzUY:matrix.xwiki.com/$_8ThMMtGtfZ_jT86_0DW1Odj262FxQy4tup7iqS9fcA?via=matrix.xwiki.com&via=matrix.org&via=envs.net
=> relax HSTS header checkup to only require a max age

www/common/translations/messages.json, www/form/inner.js
As requested [here](https://github.com/xwiki-labs/cryptpad/issues/811), this provides a way to include questions in forms where the desired answer format is a date.
=> Date input in forms

www/form/inner.js
Default date input UI in Forms changed to Flatpickr for consistency.
=> Forms date input -- changed date picker

www/form/condorcet.js, www/form/inner.js
Method names and details tag now compliant with Weblate.
=> Changed method choice/details tag for Weblate translation

www/form/inner.js
* Can now input decimal numbers in text (type: number) questions ([issue here](https://forum.cryptpad.org/d/88-decimals-in-number-type-text-field))
* Fixed issue with the "required" condition not working with different text question types #1007 
* Fixed issue with ability to bypass "required" condition by backspacing #1014
=> Form bugfixes

customize.dist/src/less2/include/forms.less
- changes were too widely scoped
- will return to the button styles for the next release but restoring things as they were for now
=> Fix font-weight of buttons

customize.dist/src/less2/include/alertify.less, www/common/common-interface.js
the panel could not be closed previously
=> Add scroll to about panel on small screens

customize.dist/src/less2/include/sidebar-layout.less
I added this regression to 5.4.0. There were a couple of buttons affected by this comment.
=> Uncommented button styling

customize.dist/pages/index.js, customize.dist/src/less2/pages/page-index.less
=> Fix homepage layout issues on small screens

customize.dist/src/less2/include/sidebar-layout.less, customize.dist/src/less2/include/toolbar.less, www/calendar/app-calendar.less, www/kanban/app-kanban.less
this branch contains some fixes of mobile UI issues
=> Mobile Fixes

lib/http-worker.js
https://github.com/cryptpad/cryptpad/issues/1277
=> Use correct mime type for .wasm files

customize.dist/src/less2/include/alertify.less, customize.dist/src/less2/include/markdown.less, customize.dist/src/less2/include/toolbar-history.less, customize.dist/src/less2/include/toolbar.less, lib/challenge-commands/totp.js, lib/storage/file.js, www/admin/app-admin.less, www/calendar/app-calendar.less, www/common/common-interface.js, www/common/common-ui-elements.js, www/common/inner/share.js, www/common/media-tag.js, www/common/outer/async-store.js, www/common/outer/http-command.js, www/common/proxy-manager.js, www/common/sframe-common.js, www/convert/inner.js, www/teams/app-team.less
- either removed or changed the comment type
=> Clean old // XXX comments

docker-compose.yml, www/common/application_config_internal.js, www/common/common-constants.js, www/common/common-ui-elements.js, www/teams/inner.js
```
AppConfig.maxPremiumTeamsSlots = 10;
AppConfig.maxPremiumTeamsOwned = 10;
```
=> Option to increase team slots for premium users only

www/form/inner.js
=> Date question datepicker/input field now displays correctly 

www/kanban/inner.js
Fixes #1325. Deleted kanban items now no longer appear in the export file.
=> Kanban item export

www/common/common-util.js, www/form/inner.js
=> Fixes issue with duplicating choice/checkbox grid questions

www/calendar/inner.js
=> Calendar datepicker on mobile now easily toggled 

www/common/inner/access.js, www/common/outer/async-store.js, www/common/outer/mailbox-handlers.js
Fixes #1337. A shared folder shared with contacts who have also been added to an enabled access list can now be accessed by contacts without having to refresh their drives.
=> Shared folder access list

www/common/cryptpad-common.js, www/common/inner/access.js
=> Fix access modal issues after password change

install-onlyoffice.sh
See Sometimes OnlyOffice documents can not be loaded: https://github.com/cryptpad/cryptpad/issues/1489
=> Workarounds for missing OnlyOffice methods

www/common/translations/messages.it.json
Translations update from [CryptPad Translations](https://weblate.cryptpad.org) for [CryptPad/App](https://weblate.cryptpad.org/projects/cryptpad/app/).
Current translation status:
=> Translations update from CryptPad Translations

www/common/onlyoffice/inner.js
https://github.com/cryptpad/cryptpad/issues/1500
=> Fix OO images when OnlyOffice was reloaded

install-onlyoffice.sh
https://github.com/cryptpad/cryptpad/issues/1572
=> Fix broken OnlyOffice Document

www/calendar/app-calendar.less, www/calendar/inner.js, www/common/common-interface.js
This PR aims to fix the following issues
=> Accessibility improvements to modals

www/teams/inner.js
Hello,
This PR fixes the following #1193
=> Teams Card List

www/common/drive-ui.js
Hello,
This PR fixes  #1609 , making the button accessible for keyboard navigation.
=> `+New` button fixes on Drive

customize.dist/src/less2/include/dropdown.less, www/calendar/app-calendar.less, www/common/common-ui-elements.js
Hello,
This PR fixes #1612 :
- fixes icon spacing on dropdown buttons (calendar modal)
- fixes uneven spacing between buttons (calendar modal)
=> Calendar modal UI fixes

customize.dist/pages/features.js, customize.dist/src/less2/pages/page-features.less
Hello,
This PR fixes #1604, adding a missing margin between card components.
=> Missing margin on Features page

www/drive/inner.html
Hi,
This PR focuses on #1607, that removes unnecessary focus inside the drive
=> Drive focus fixes

customize.dist/pages/features.js, customize.dist/pages/index.js, customize.dist/src/less2/include/alertify.less, customize.dist/src/less2/include/checkmark.less, customize.dist/src/less2/include/drive.less, customize.dist/src/less2/include/forms.less, customize.dist/src/less2/include/infopages.less, customize.dist/src/less2/include/sidebar-layout.less, customize.dist/src/less2/include/tokenfield.less, customize.dist/src/less2/include/toolbar.less, customize.dist/src/less2/include/variables.less, customize.dist/src/less2/pages/page-features.less, customize.dist/src/less2/pages/page-index.less, www/admin/app-admin.less, www/calendar/app-calendar.less, www/kanban/app-kanban.less, www/settings/app-settings.less, www/teams/app-team.less
Hello,
This PR aims to fix design inconsistencies across the entire app: #1506
Pages targeted in this PR are:
=> Focus style fixes

customize.dist/src/less2/include/checkmark.less, www/form/app-form.less, www/form/inner.js
* Fixes insufficient spacing between elements on form settings modal (#1644)
=> Form settings modal accessibility

lib/hk-util.js, lib/workers/db-worker.js, www/common/outer/async-store.js, www/common/sframe-common-history.js, www/common/sframe-common-outer.js
Prevent server Out-of-Memory crash caused by document history
=> History limit

www/common/outer/messenger.js
=> Fix contacts page not loading

www/common/sframe-common-outer.js
This PR updates the iframe title, closing #1606.
The change has been tested with NVDA.
=> Change iframe title

www/common/drive-ui.js
=> Stops selection of all other trashed files when restoring single file

www/common/inner/access.js, www/common/inner/common-modal.js
* 'Request edit' button in Access modal no longer displayed if user already has edit access (fixes #1027)
=> 'Request edit' button

customize.dist/messages.js, customize.dist/src/less2/include/toolbar.less, www/admin/inner.js, www/calendar/inner.js, www/code/inner.js, www/common/onlyoffice/inner.js, www/common/sframe-app-framework.js, www/common/toolbar.js, www/diagram/inner.js, www/drive/inner.js, www/form/inner.js, www/kanban/inner.js, www/notifications/inner.js, www/pad/inner.js, www/profile/inner.js, www/settings/inner.js, www/slide/inner.js, www/teams/inner.js, www/whiteboard/inner.js
This PR introduces a skip link to improve accessibility, allowing users to quickly navigate to the main content. 
Fixes #1202
=> Add Skip Link

www/notifications/inner.js
Hello,
This PR improves the keyboard navigation for the sidebar on: https://cryptpad.fr/notifications/#all.
Fixes #1773
=> Notifications sidebar: Fix keyboard navigation issues

customize.dist/messages.js, www/admin/inner.js, www/common/inner/sidebar-layout.js
Minor adjustments to the Admin UI PR(#1801) that has been merged already
=> Accessibility fixes to Admin UI

customize.dist/messages.js, www/admin/inner.js, www/form/inner.js, www/settings/inner.js
This PR adds descriptive error message in multiple areas:
-  #1762 
-  #1763
-  #1764
-  #1790
-  #1791
=> Add descriptive error messages

customize.dist/messages.js, customize.dist/translations/messages.js, www/form/app-form.less, www/form/inner.js
Fixes #1587 (Form question blocks now have up/down buttons on mobile, allowing re-ordering without drag and drop)
=> Buttons for moving question blocks in Forms (mobile)

customize.dist/src/less2/include/toolbar.less, customize.dist/translations/messages.js, www/common/translations/messages.json, www/profile/app-profile.less, www/profile/inner.js
This PR aims to make the profile layout responsive to smaller screen sizes, fixing [#1090 ](https://github.com/cryptpad/cryptpad/issues/1090)
=> Fix profile layout on small screens

lib/eviction.js, lib/pins.js, lib/storage/blob.js, lib/storage/file.js, lib/workers/index.js, scripts/check-account-deletion.js, scripts/compare-pin-methods.js, scripts/tests/test-pins.js
* Stream pin logs when computing list of pinned documents
* Properly delete blob metadata files from archives
* Clean old blob proofs from archives
=> Fix eviction issues

customize.dist/messages.js, www/common/onlyoffice/inner.js
https://github.com/cryptpad/cryptpad/issues/1888
=> Show error message when x2t conversion fails in OO editor

.github/workflows/test-trigger.yml
- Adds a .yml file which triggers the instance setup and test runs in /e2e-test-suite
=> Test workflow

www/slide/slide.js
- Can exit presentation mode on mobile (fixes #1105 ; fix by @lemondevxyz )
=> Can exit presentation mode on mobile

www/diagram/inner.js
* Diagram history read-only view now displays correctly (fixes #1663)
=> Diagram history
