cryptpad/cryptpad

- NetfluxWebsocketSrv.js
- config.js.dist
- server.js
- storage/LogStore.js
- storage/README.md
- storage/amnesia.js
This probably should have been two different branches, but the bulk of the changes implement (optional) removal of channels some time after the last participant in a channel has disconnected.
The configuration object is now supplied as a third argument to the socket server, and with that in place I also decided to make STDOUT logging configurable (instead of via a constant defined within the server).
Channel removal is configured via two variables:
1. `removeChannels`, which is treated as a boolean (defaulting to 'false')
2. `channelRemovalTimeout`, which must be a number (defaulting to 60000 (one minute))
The only database adaptor which currently implements this behaviour is `amnesiadb` (which only exists in memory anyway).
Databases which do not implement this functionality will …
> Remove empty channels

- readme.md
Added some extra clarification with regards to pad content changes by 3rd-parties without the private key. See #28
> clarify how mitm attack is mitigated

- server.js
The original custom file handler code caused the server not sending the content-type header in some cases. This killed the site e.g. when using CloudFlare - safari tried to download the index.html instead of rendering it and chrome displayed the source code.
I might be missing something but I replaced that code with 2 simple express.static handlers - which handle content type (among other things) correctly
> Using express.static instead of custom handler

- www/code/main.js
- www/common/cryptpad-common.js
- www/pad/main.js
- www/poll/main.js
- www/slide/main.js
Currently, if users hit the back button while on newly created pad, they will navigate to `/pad/` instead of the home page, so they have to hit 'back' a second time.
This change makes changes to the hash _not_ occupy an additional place in the history, which is a little more intuitive.
> use replaceState if available

- customize.dist/main.css
- customize.dist/src/cryptpad.less
- customize.dist/translations/messages.es.js
- customize.dist/translations/messages.js
Hola! :es:
So I noticed there were lots of issues with the Spanish translation. It looked very machine translated, there were some extra/overwritten language keys, and there were some keys that were only half translated.
I rechecked the whole thing and fixed it up so that it now has natural grammar, and unified translations for all things (it was referring to documents as pads/documents).
Also took upon the opportunity to add some missing `alt` tags in the English file :)
> Fixed Spanish translation

- customize.dist/src/less/toolbar.less
- customize.dist/toolbar.css
- www/drive/file.css
- www/drive/file.less
- www/drive/main.js
- www/poll/index.html
Some CSS fixes:
- Fixed textarea in poll being too large causing overflow
- Fix title input in pads being too large when on mobile/zoomed in
- Toolbar buttons are now always the intended color (even when you have a custom theme)
- Fixed the context-menu not appearing at the right place when using the dropdown arrow (mobile/zoomed in)
> Some CSS fixes

- readme.md
The delete/reset instructions were directly after the upgrade instructions. Figured its useful to put a header and a warning to prevent running those commands by mistake when upgrading.
> Adding a warning and header to delete/reset docs

- customize.dist/pages.js
- customize.dist/src/less/cryptpad.less
- Removed ".first" class from Register button
- Increase spacing between buttons
> Issue #151: Spacing between "Log-in" and "Register" buttons

- customize.dist/translations/messages.de.js
out.presentSuccess wasn't translated to german yet, added german translation. (I'm a native speaker of german.)
> Translated missing out.presentSuccess to german

- container-start.sh
- docs/cryptpad-docker.md
This fixes an error during container startup due to interpolating a
$STORAGE value that may contain slashes or other "active" characters:
...
Using secure websockets: false
Using storage adapter: ./storage/file
sed: bad option in substitution expression
I guess this is the same as the TODO item mentioned in the
docs/cryptpad-docker page.
Also add a trailing ',' in the search expression to avoid substituting
in the comment above the actual definition:
/*  If Cryptpad is proxied without using https, the server needs to know.
*  Specify 'useSecureWebsockets: true' so that it can send
...
By the way, I have a related question: I'm using cryptpad behind an nginx reverse proxy (SSL). Should I specify `useSecureWebsockets: true` or false? I'm a bit confused by the wording.
Best, Thomas
> Properly escape sed match/replace expressions

- www/invite/index.html
- www/profile/index.html
Noticed there were some residual "Cryptpad" titles, so I changed the casing on those, as it would flash briefly in the title bar 📸
> Use CryptPad everywhere instead of Cryptpad in titles

- customize.dist/src/less2/include/colortheme.less
- www/pad/app-pad.less
- www/poll/app-poll.less
We have discussed this over IRC and email, I think this commit improves the ability to theme cryptpad by moving some colours to colortheme.less under customize.dist.
> Theming improvements as proposed from dyne

- .dockerignore
- .travis.yml
- Dockerfile
This fixes the `Failed at the heapdump@0.3.9 install script 'node-gyp rebuild'.` issue so docker builds again.
> Fix docker build

- server.js
It appears that even though terms.html, index.html etc ("main pages") are in the customize.dist folder, we could not customize these pages by creating a similarly-named file in the customize folder.
Adding this line reuses the same mecanism as lines 127-128 to recover this behavior on main pages.
> Fixed customization of main pages

- www/logout/index.html
- www/logout/main.js
This PR adds a /logout URL that allows destroying user session (local storage, session storage & indexedDB) with a minimum number of loaded dependencies.
This is useful for SSO systems that need to log users out of any protected application by loading a logout URL
> add a logout page

- container-start.sh
Update docker run script to bust the cache on each run. This is to ensure there aren't left over cache items when a container is started with a new version or the config has been changed heavily.
> Update docker start script to bust the cache on each run

- Dockerfile.arm64
Cryptpad will run on arm64 but needs a totally different base image and some other Dockerfile tweaks. This PR adds a Dockerfile.arm64 that can be used to deploy on arm64 boards/VPS instances like the Raspberry Pi or the Scaleway arm64v8 offerings.
> Add Dockerfile for arm64 support

- Dockerfile
Add port 3001 to the exposed ports list (used by the http safe port in the standard config)
FIX the STORAGE var so it doesn't cause a subtle error when the config.js file is parsed at runtime. This fixes the storage limits from being applied to users and also allows the api/config file to properly pickup a number of config changes that aren't picked up in the previous form of the Dockerfile
> Minor Dockerfile updates/fixes

- rpc.js
The aufs storage driver in docker will not work with the rename Fs call. This patch updates to use the move Fs call instead which works with the aufs Docker storage driver.
> Fixup docker rename calls (addresses #244)

- customize.dist/translations/messages.de.js
- customize.dist/translations/messages.js
Hi, I didn't ilke the strings for the autostore settings (#270).
I changed them and added the german translations for the whole "choose autostore" feature.
I hope this suffices, do you need me to test them in the webUI or something similar?
> Changed the description for autostore settings (en/de)

- customize.dist/src/less2/include/app-print.less
- www/code/app-code.less
- www/code/inner.html
- www/code/inner.js
- www/common/translations/messages.js
Hi,
This adds print functionality to the `/code` pad, as per feature request [#198](https://github.com/xwiki-labs/cryptpad/issues/198).
It's based on the implementation in the `/slide` pad. A new button is added under the "*More actions*" drop-down menu.
Couple points to note:
- Print button now has a more generic title text "*Print your document or export it as a PDF file*". This would now apply to the presentation pad as well, so translations will need to be updated. Alternatively, a custom button could be made for each type of pad with unique text.
- The final margins and page orientation depend heavily on local printer setup, so have been left to default for now (tested in Firefox, Chrome).
Let me know if any additions/fixes are required.
> Issue #198: Add printing option to /code

- docs/example.nginx.conf
Made CSP syntax valid. There were arguments for e.g. blob: oder data: missing
> Made CSP syntax in nginx example conf valid

- Dockerfile
2 volumes were missing from the docker file. This PR adds them to the main Dockerfile.
They are present in the docker-compose.yml so this should be a non-issue for most users.
> Add 2 missing volumes for blobs

- bower.json
- lib/load-config.js
Hi,
I am part of the NixOS Foundation. As part of the NLNet Zero grant we are helping accepted projects to package their project into nixpkgs. The goal is to provide a unified and composable way for all the grant's project to be used.
This PR includes a few changes that would make it easier to package cryptpad. A WIP package is available over there: https://github.com/NixOS/nixpkgs/pull/61513
The biggest outstanding difficulty that hasn't been addressed is that the project assumes that it's running from withing the source root. While a package generally has a binary installed in the PATH, the source somewhere in the /usr/lib and the data somewhere under /var like /var/lib/cryptpad. If you want cryptpad to be available in other package managers I recommend making these changes. If you want …
> Nix packaging

- www/kanban/jkanban.js
This patch moves the button to add new items to kanban boards to the
column headers.
The reasoning behind this change is that on larger boards the buttons at
the bottom may be pushed far away from the actual content, causing users
to constantly scroll up and down over the whole page just to add new
items. See the real-world example below.
This also helps on mobile devices since you may not see all of the
columns there due to the limited screen space. This means that you have
to remember which column you are working on to not accidentally add
items to the wrong column. This patch makes it clear to which  column
users add items since the button now resides next to the column title.
---
Example illustrating the issue to solve:
> Kanban: Move “Add Item” to Header

- www/kanban/jkanban.js
This patch moves the button for adding new columns to kanban boards from
the top-right to the bottom-left. The reasoning behind this is that it's
not very often used (often only at the beginning when setting up the
board) but it is constantly taking space away from the columns. This is
annoying especially on mobile devices where it even moves all of the
columns to the left, leaving a larger border on the right.
> Kanban: Move “Add Column” to Bottom

- lib/load-config.js
CryptPAD now terminates and does not fallback to default config if the custom config is faulty.
The error in the custom config is logged to the terminal now.
Signed-off-by: Adrian Nöthlich <git@promasu.tech>
> Log errors in faulty custom config file

- server.js
Noticed I was getting the warning and tracked it down to a missing `config.`
> Check httpSafeOrigin in config variable

- lib/log.js
The script `evict-inactive.js` calls `Log.shutdown()` at the end, which currently fails if logging to disk has been disabled via `logPath`.
> Add shutdown() to non-disk logger

- lib/historyKeeper.js
Hi cryptpad-team,
since commit f86196e40adfccade922e63bba5dafbff20538fe config.defaultStorageLimit cannot be zero anymore. I suppose this might break some configurations.
While https://github.com/xwiki-labs/cryptpad/blob/c8c98b57479637484b36ba43e14c45671cdcffe8/lib/load-config.js#L35 allows it to be >= 0, https://github.com/xwiki-labs/cryptpad/blob/f86196e40adfccade922e63bba5dafbff20538fe/lib/historyKeeper.js#L82 requires it to be > 0.
Greetings,
Alex
> Allow config.defaultStorageLimit to be zero bytes

- customize.dist/messages.js
Have a good day.
As cited at #609 there is a problem at naming _finnish_ so this change is needed in order to provide correctness.
> Finnish language renamed in a correct way

- docs/cryptpad.service
/home/cryptpad/cryptpad/cryptpad seems one cryptpad too many, and it does not match the sample value of WorkingDirectory above
> Set reasonable env value for $PWD

- readme.md
Changed a link from an empty wiki-page to one I thought should be there. I'm assuming the contribute page changed at some point and someone forgot to fix the link?
> Fixed link

- config/config.example.js
- lib/historyKeeper.js
- lib/log.js
- lib/workers/db-worker.js
Mixing code and data in the same writable directory is a security risk. Mitigating it requires running CryptPad as a user that doesn't have write permissions to the source tree, and configuring all data paths to be under a directory that user can write (e.g. source under /home/cryptpad/cryptpad and data under /var/lib/cryptpad).
Without these patches, some places in CryptPad fall back to PWD based paths and fail with EACCESS.
> Support non-writable working directory

- customize.dist/translations/README.md
- readme.md
Here is a small proposal to include some Weblate "widget" on our repository `README.md` files. I believe it would facilitate translation contributions.
Right now, potential contributors have to go through Weblate projects, search for the language they might know. Having these stats right on our repo they'll get the information sooner and might get motivated to contribute.
See how it currently look:
As discussed with @davidbenque, we don't really like the look of the widget. The fact that the languages aren't sorted in particular order isn't great too. We might want to try other widgets, but [the Weblate page looks kinda broken](https://weblate.cryptpad.fr/widgets/cryptpad/?component=app) (probably an HTTP/HTTPS mismatch).
> add Weblate widget showing language translation progress

- www/common/outer/worker-channel.js
There was code to handle unparseable messages from things like third party browser extensions but it caught a JSON parsing error, logged an error and then continued, which would throw an unhandled exception trying to read the `ack` property of `data` which had been left as `undefined`.
Add a `return` to abort execution of the handler function and ignore the message instead. Also changes the error to warning, since it's not a fatal error. Add a comment to clarify the behaviour.
From the existing comment, it looks like this was the original intention of the code, but the `return` was simply missed.
> Make unparseable message non-fatal

- www/common/boot2.js
As requested [here](https://github.com/xwiki-labs/cryptpad/issues/759), if an AppConfig.defaultDarkTheme variable is added to application_config.js and set to true, this sets the theme to dark by default irrespective of browser settings.
> Default dark theme switch

- docs/example.nginx.conf
The API server started forbidding remote embedding by default a number of major versions ago, but we didn't update the default value for `$allowed_origins` in the example NGINX config. This patch updates its default match that of the API server.
As per usual, the comment is probably the hard part, so it might be worthwhile to worker on a better/clearer phrasing.
> invert NGINX settings to forbid remote embedding by default

- www/common/onlyoffice/inner.js
- www/common/sframe-common-outer.js
Fixes #1061
This commit adds a 'Make A Copy' to all onlyoffice applications theortically. Though, I only tested sheets since that's all I had in my toolset.
The toolbar works through adding buttons with 'createButton' in `./www/common/common-ui-elements.js:569` and there are (thankfully) premade buttons. That means that buttons like 'Export', 'Make A Copy', 'Import', etc can be created by supplying the type and a boolean indicating the right side.
But most uses of createButton are through
`./www/common/sframe-common.js:106` which is the same underlying function of `common-ui-elements.js` but with the first two arguments skipped.
Anyhoo, this was long. Basically, all this commit does is add two lines at `./www/common/onlyoffice/inner.js:2851`.
> add a "make a copy" element to onlyoffice applications

- CHANGELOG.md
- customize.dist/src/less2/include/drive.less
> provide visual feedback that a dragged item can be dropped into the drive's tree when hovering
I noticed a while back that dragging an element from the drive's main pane to the tree did trigger any visual feedback while hovering with the element. This made it somewhat unclear whether the item was able to be dropped. Aside from the visual cues, everything does seem to work as expected when the element is dropped, so we just need better styles.
This PR adds those styles to the main document tree, the templates category, and the trash - but not on un-droppable categories like "recent" or "tags".
The styles are applied using a less mixin, so it should be simple to add any other styles, such as a contextual cursor.
> provide visual feedback that a dragged item can be dropped

- www/common/onlyoffice/inner.js
Fixes #1073 
Normally, copied CryptPad files have a " (copy)" suffixed to them but OnlyOffice doesn't because it has different internal architechture.
Copied OnlyOffice files can be identified by two attributes: a non-empty title and template data.
Since OnlyOffice files cannot be just copy and pasted, I resorted to modifying their metadata through metadataMgr in `./www/common/onlyoffice/inner.js:244`
Essentially, this commit check if a file is a copied file. If it is, it updates the title. It doesn't actually copy the file but merely modifies the title after it has been copied.
Note: I only tested this on OnlyOffice Sheets because I couldn't figure out how to run the other OnlyOffice applications.
> add " (copy)" to copied OpenOffice files

- www/common/common-interface.js
- www/settings/inner.js
this is just a minor usability improvement - the user's cursor is automatically set inside the OTP input field when they are prompted. Otherwise they have to select the field manually.
> set cursor in OTP input field

- customize.dist/ckeditor-contents.css
closes #1111
the app Rich Text, codename pad, has unnecessary right padding for all lists. This makes it quite frustrating to edit in mobile environments.
This commit basically removes all unnecessary right padding for all lists.
Here's a screenshot on iPhone SE simulation.
> remove unnecessary right padding from all lists in Rich Text(pad)

- customize.dist/src/less2/include/forms.less
- www/settings/inner.js
I fixed the regression introduced with the 2FA settings styling, now the disabled tabs are grey instead of red. #1157
> Fixed the color of access modal disabled tabs

- docs/cryptpad.service
Since we updated the NodeJS installation method in the previous release, we need to update the systemd service file provided.
> change NodeJS path to match new recommended installation method

- www/admin/inner.js
I would like to suggest a small change to localize the online status (true or false) in generated account reports. See the following example showing the German translation.
Before:
After:
> Localize online status in generated account report

- customize.dist/src/less2/include/sidebar-layout.less
Fixes #1101 
Here's a screenshot
> add even space between category buttons

- www/kanban/app-kanban.less
Fixes #1039 
This commit adds some padding to the cards container in Kanban for better mobile user experience.
Here is a demo:
https://cryptpad.fr/file/#/2/file/z8X7DfDPkNVwepC3kaMbH0S5/
> add vertical padding to Kanban card container

- www/calendar/inner.js
- www/calendar/recurrence.js
This pull request proposes the following changes to fix the issue #1275:
1. In the case where a single instance of a repeating event is moved from a calendar to another it is copied in the target calendar as a single event and added as an exception of the recurrence rules in the source calendar.
2. Due to the current implementation of recurring event, it is not possible to perform the two cases described hereunder. Henceforth, these cases have been disabled in the UI.
- Only move the first element of a repeating event (which contains the recurrence rules) from a calendar to another.
- For the same reason, we cannot move a repeating event to another calendar from a certain date.
4. Adding explanation messages in forms of warnings as to why these options don't appear in the confirmation …
> Calendar: handling the move of repeating events from a calendar to another

- www/calendar/app-calendar.less
- www/calendar/export.js
- www/calendar/inner.js
- Add a description field when creating and editing an event as per #1171 
- This field supports markdown information to format the description.
- Integration in the detailed popup view of [tui.calendar](https://github.com/nhn/tui.calendar).
- Support for plaintext/markdown export
- html export is not supported yet (https://www.rfc-editor.org/rfc/rfc5545#section-3.2.1)
Note: Two new descriptions keys : `calendar_desc` and `calendar_description` are to be added upon version release.
> Feature: Add a description field for calendar events

- www/calendar/export.js
This pull request addresses two (related) issues:
- Fix a linter error introduced by #1299 from `ical.min.js` which was not made with requireJS in mind.
- As `ical.min.js` is now loaded on the whole file and not only used by the ics import module, we removed the `require(…)` from it and re-indent the whole block.
> Reformat `www/calendar/export.js`

- www/common/outer/calendar.js
Fix #1306: stopping the recurrence on a calendar event wipes previous punctual changes.
Also fix the behavior when resuming the recurrence to be consistent with the previous fix (otherwise it may remove punctual changes on edge cases).
> Fix a bug with stopping the recurrence of a calendar event

- www/common/cryptpad-common.js
- www/form/inner.js
Fix the bug where importing a template in form raised an error: #1261
While fixing it, set a behaviour upon importing template:
- Now, the settings on allowing anonymous responses and enforcing anonymous responses are stored into the template and override the previous ones.
- Usecases: creating a template for anonymous poll and a template for registered-only users.
> Fix the error upon importing a template in forms (#1261)

- www/form/export.js
- www/form/inner.js
- www/whiteboard/export.js
This PR tackles multiple issues, namely:
1. #1267: this issues is solved with 51abbb484fadf43e9ce2691b305eede48eb70378, it was an issue with the export module for the whiteboard application which automatically detects the size of the exported image, which is set to be 0×0 in the case of empty whiteboard. This kind of image could not be exported and resulted in a missing file. To sort this out, we decided to set a default size of 600×600 pixels for empty whiteboard to be consistent with the other empty-files export.
2. While solving this, we also noticed that other whiteboard exports (from drive) were transparent PNG files (of the right size however) as described in #1324. This is fixed in 0005b933e98f3f200364bfa1bef79cd7fe94c7a9 and was due to a missing rendering of the canvas.
3. …
> Fix a few export-related issues

- customize.dist/src/less2/include/drive.less
- www/common/drive-ui.js
Fixes #1351. The icons are only displayed for drive files in list mode, or, when in grid mode, as part of the file name, only when the item has a thumbnail.
> File icons in drive

- customize.dist/ckeditor-config.js
- www/pad/inner.js
- www/pad/links.js
Hi,
Here are some fixes that:
* Restore contextual menu to be able to edit tables again (as mentionned in [this comment](https://github.com/cryptpad/cryptpad/issues/1358#issuecomment-1886761694)).
* Filter out some non-displayed content used by ckeditor on chrome for clipboard management that caused duplicated elements in table of contents (#1336).
* Anchors that are created by selecting a text before creating the anchor are now working within the Richtext app in CryptPad (#1226)
> Fix richtext issues (#1336 + ~#1358 + #1226)

- .eslintrc.js
- www/common/onlyoffice/inner.js
I also started to use Promises and removed some unused code.
https://github.com/cryptpad/cryptpad/issues/1420
> Do not allow OnlyOffice comments in view mode

- customize.dist/template.js
The ssoauth page is called without a trailing slash (presumably because of the GET-parameters). Therefore he regex for calling the main.js does not match and the rendered `/ssoauth` page is without function.
Fixes #1410
> Fix ssoauth path regex

- www/common/outer/mailbox.js
This PR fixes the near-infinite creation of notifications on team acceptance as reported in #1399.
It disables re-executing notification handlers when replaying history.
> Fix Notifications replaying (#1399)

- customize.dist/src/less2/include/notifications.less
Hello,
This PR fixes #1465 by removing drawing over the background when mouse hover some elements in the notification dropdown. Especially the dismiss (❌) button that was visible as it is not rounded.
> #1465: unsharp the corners when hovering the dismiss button on notification dropdown menu

- lib/api.js
- lib/commands/admin-rpc.js
- lib/commands/quota.js
- lib/stats.js
- www/admin/inner.js
* Send aggregated stats to CryptPad.fr (only for instances that opted-in)
* Number of registered users
* Number of maximum concurrent users since last ping (total, registered, unique IP)
* Also includees detection and workaround for a possible minor memory leak
* Improve the way we count the number of registered users on an instance
> Server fixes and aggregated stats

- customize.dist/src/less2/include/toolbar.less
- www/common/sframe-common-codemirror.js
This PR aims to fix #1208, so that every user can navigate into and out of text editors using only the keyboard
> Fix locked focus on text editors

- lib/api.js
Currently, `Fs.writeFile(fullPath, 'PLACEHOLDER\n', w());` always fails silently.
It fails **silently** because the error is not checked on `Fs.writeFile`.
And it **fails** because the block folder is not created before we try to write the file.
As a consequence, the first time you launch the server, the `placeholder.txt` file is not created.
When you run the checkup script, it fails to find the file but creates the missing folder as, as soon you ask to store a proper block, because the called logic has the `Fse.mkdirp` logic, and thus the folder is created. So, on the next restart of Cryptpad, the placeholder.txt file can be created, and magically, the checkup script succeed.
I create the block folder and check for error before trying to create `placeholder.txt`, then I also check for …
> Create the block folder at boot

- customize.dist/src/less2/include/drive.less
- customize.dist/src/less2/include/icons.less
- www/common/common-interface.js
This PR aims to fix accessibility issues for the `Ctrl+E` modal:
- #1558
- #1506  (updated the styling for this modal)
> `Ctrl+E` modal fixes

- customize.dist/messages.js
- www/common/outer/history.js
- www/common/outer/roster.js
- www/report/main.js
- www/teams/app-team.less
- www/teams/inner.js
* A "Trim History" button or an automatic script?
* Make sure the .offset is correctly used by the server
> Team roster channels slow down team members accounts

- www/common/common-ui-elements.js
Hi,
This PR fixes a bug found in testing : I've added the option to `Shift-Tab` through the `Ctrl-E` modal when it's opened inside an app.
> `Shift-Tab` option for `Ctrl-E` modals

- lib/workers/index.js
* Fix issue with newly spawned workers added twice to the list after a crash
* This meant the new worker had twice as much tasks as the others
* Fix issue when dispatching tasks of a crashed worker to the other ones
* The wrong data was sent to the other workers so these tasks couldn't be executed
> Server worker issues

- www/form/inner.js
This PR fixes a keyboard trap found inside the Form description. I've added the `Esc` option in order to remove the focus from the text field (this option is also used for other CodeMirror usages), fixing #1638.
> Fix keyboard trap inside Form description

- www/common/common-ui-elements.js
- www/common/drive-ui.js
This PR disables the use of arrow keys inside the drive while a modal is open, fixing #1660.
Previously, arrow keys could still be used to navigate files in the background, which could lead to unintended behavior or conflicts when interacting with the modal. Now, the arrow keys are disabled inside the drive while a modal is opened.
> Disable arrow key navigation in the drive while modal is active

- www/common/drive-ui.js
The fix improves keyboard accessibility by enabling the same behavior (click action) for users interacting with Ctrl+E elements using the keyboard. This PR closes #1725.
> Simulate click action for keyboard users in Ctrl+E modal

- www/common/outer/userObject.js
* When a link is moved to the trash, and the browser page refreshed, it now stays in the trash until it is removed / destroyed instead of disappearing (fixes #1696)
> Prevent links in trash from disappearing after drive reload

- customize.dist/src/less2/include/checkmark.less
- www/form/app-form.less
Hello,
This PR addresses multiple spacing and padding issues in the Forms app:
- Fixes insufficient spacing between elements in the form settings modal ([#1644](https://github.com/cryptpad/cryptpad/issues/1644)).
- Fixes missing padding for radio and checkbox buttons inside form questions ([#1642](https://github.com/cryptpad/cryptpad/issues/1642)), which also resolves issue [#1507](https://github.com/cryptpad/cryptpad/issues/1507). This ensures better distinction between options.
> Fix spacing issues in Forms 

- customize.dist/src/less2/include/toolbar.less
This PR fixes the weird padding of the "No notifications" section inside the notifications dropdown
> No Notifications padding issue

- www/common/cryptpad-common.js
- www/form/templates.js
This PR proposes a solution for:
The solution for #1718 changes the behaviour of CryptPad as it creates a “quick schedule poll”-named file instead of the default generated filename. However it coincides better with real templates. When creating a file, it inherits the template name.
> Fix some form storage-related bugs

- lib/hk-util.js
- lib/storage/file.js
- lib/workers/db-worker.js
- lib/workers/index.js
* this would be a workaround against a small memory leak
* includes the fixes about server memory related to document history
> Reload server subprocesses after a configured number of tasks

- www/common/drive-ui.js
With this change, we now sort "folder 2" *before* "folder 10".
> Sort files and folders with "natural" sort

- www/common/drive-ui.js
- www/common/make-backup.js
- www/common/userObject.js
- www/settings/inner.js
As reported in #1782, the anonymous file download was not working. Neither from the drive, nor the settings interface.
This PR addresses these two problems.
> Fix anonymous drive download

- install-onlyoffice.sh
`--check` is useful for anyone who wants to check if their OnlyOffice
installation is up to date without actually installing it.
The `--rdfind/--no-rdfind` commands serve a few purposes:
1. It makes it clear that `rdfind` can still run even if you specify `--check`.
2. People can ensure that `rdfind` runs by specifying `--rdfind`, which
helps if they accidentally uninstall `rdfind`.
3. People can now skip running `rdfind` even if they have `rdfind`
installed.
> Add `--check`, `--rdfind`, `--no-rdfind` options to `install-onlyoffice.sh`

- www/common/sframe-common.js
I believe that there used to be some event handlers for `<a>` tags in the sandbox which ensured that relative URLs were opened under the main/outer domain rather than the sandbox/inner one. This seems to have stopped working in one of the recent releases. I only noticed when I opened an old markdown document which used relative links between different pads.
I realized that this functionalty could be re-implemented much more simply by using a [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) tag. Adding such a tag with an `href` attribute pointing to the outer domain causes all relative links to be interpreted as relative to that URL, rather than to the sandbox (which is unlikely to be anyone's intended behaviour).
Types of URLs other than relative ones should not …
> Treat relative URLs in the sandbox as relative to the outer domain

- www/form/app-form.less
This PR aims to fix the overflowing of long questions in Forms app and the weird sizing of the Required button of a question, mentioned in [#1722 ](https://github.com/cryptpad/cryptpad/issues/1722)
> Fix long question text overflow and weird sizing of the required label in forms

- www/common/translations/messages.de.json
- www/common/translations/messages.pl.json
- www/common/translations/messages.zh.json
Translations update from [CryptPad Translations](https://weblate.cryptpad.org) for [CryptPad/App](https://weblate.cryptpad.org/projects/cryptpad/app/).
Current translation status:
> Translations update from CryptPad Translations

- www/common/media-tag.js
- www/file/file-crypto.js
* Fix an issue with the "increment" function from file-crypto (and copied to media-tag.js)
* Thanks @ansuz for catching it and providing a fix
* Note that this couldn't affect users as it would require to upload a file too large to be stored on any hardware
> Fix u8 increment issue in file-crypto

- customize.dist/messages.js
- customize.dist/src/less2/include/creation.less
- customize.dist/src/less2/include/loading.less
- www/common/common-interface.js
- www/common/common-ui-elements.js
This PR fixes the user scenario for creating a new document by addressing accessibility issues in the "Create New Document" modal. Keyboard users and screen reader users couldn't interact with the page effectively: focus didn’t move correctly, some elements trapped the keyboard, and screen readers couldn’t read the modal content.
This PR includes the following fixes:
- ensure there are no keyboard traps
- enable proper keyboard navigation across all focusable elements
- add visual focus outline
-  improve screen reader support:
-  add proper aria roles to elements
- update aria-label
Closes #1912 
Tested with NVDA, AxeCore
Note: I changed the merging branch because changes from this PR are connected with #1913. The other PR depends on the changes introduced here, so this PR is ready for …
>  Improve keyboard navigation & screen reader support for "Create New Document" modal

- www/diagram/export.js
Fixes an issue where `.drawio` diagram files could not be downloaded from CryptPad Drive.
FileSaver.js was receiving a raw XML string instead of a proper `Blob` or `File`, causing a `TypeError: Failed to execute 'createObjectURL'`.
- Serialize XML content using `XMLSerializer`
- Wrap it in a Blob with MIME type `text/xml`
- Ensure `.drawio` extension is added
Fixes #1819
Diagram files now download correctly without runtime errors.
> Fix diagram export

- www/kanban/app-kanban.less
- www/kanban/inner.js
This PR addresses the Kanban tags and resolves the issue by making them accessible via keyboard, closing #1809.
> Improve Kanban Tags accessibility with keyboard navigation

- src/common/recurrence.js
- www/calendar/inner.js
Events to render on the current month weren't taking into account the "day" modification of recurring events, resulting in some events not being displayed until the user loaded other months.
Example: We have an event repeating every two weeks and, at some point, we delay future occurrences by one week. If an event was supposed to occur on the last week of a month, it will now occur on the first week of the next month.
Our code was computing the events to render on a given month before updating the events with their time adjustment, meaning that in this example, the event that shifted its month wouldn't be rendered until the user computed both months (by moving back in the calendar view).
> Fix missing recurring calendar after update

- config/config.example.js
Mention new administrators management from the interface instead of relying on the configuration file.
> Update config.example.js comment for admins section
